### ISSUE TITLE
Peer feedback - Rick

### ISSUE THREAD

**Issue by RickGroot** [Vincentvanleeuwen/real-time-web-2021#1]
# Feedback
Your application looks nice, and there isn't much to change as for now.

## Repo
* File structure looks good 📁 
* Readme is clear and understandable

> Not much to say really, your repo looks good and is very understandable for a first visit. You could maybe add an image to the readme? (not necessary)

## Live site
* Great styling of the app
* What does "search for a playlist" mean? 🔍 

> Maybe instead of "search for a playlist" you can put "Join a playlist" or something like that

## Code
* Top of app.js has some commented info, this could be deleted ♻️ 
* Procfile is not necessary for a nodeJS webserver on heroku
* JavaScript had been split up 👍🏻 
* JavaScript could use some more comments 👎🏻 

> Overall your code looks clean and very understandable for someone who knows what you're trying to achieve. For outsiders there might be a lack of code comments...

**Comment by Vincentvanleeuwen** [comment]
Thanks voor je feedback!
